### PR TITLE
chore: Update description

### PR DESCRIPTION
**Pull request by rwwagner90**

### CODE REVIEW

**Comment by adrigzr** [comment]
Hi @rwwagner90,

Thanks for your contribution. Could you please change your commit message to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)? 

Something like: `chore: update package description`

Thanks!

**Comment by rwwagner90** [comment]
Just updated the description. I believe you can update it as well though, if you have write permissions.

**Comment by adrigzr** [comment]
I meant the commit message :)

**Comment by rwwagner90** [comment]
@adrigzr Is there really a need to have me pull down something I edited directly in GitHub to change the commit message? The description is up to date, and when you merge it should use the description, and if not, you can edit it when you click the merge button. Does that work for you?

**Comment by adrigzr** [comment]
@rwwagner90 the point is that we have a build stage where we check for the commit message in order to know what type of change it is to bump the version number. Nvm, I already pushed the change in the commit message.

**Pull request merged**
